### ISSUE TITLE
Build on MacOS 10.14 fails

### ISSUE THREAD

**Issue by greerso** [HorizenOfficial/zencash-apple#1]
After `LIBTOOLIZE=glibtoolize ./zcutil/build-mac-clang.sh --disable-libs -j($sysctl -n hw.ncpu)`, eventually get the error:

```shell
crypto/aes/aes_core.c:39:10: fatal error: 'assert.h' file not found
#include <assert.h>
         ^~~~~~~~~~
1 error generated.
make[2]: *** [crypto/aes/aes_core.o] Error 1
make[1]: *** [build_libs] Error 2
make: *** [/Users/greerso/zen/depends/work/build/x86_64-apple-darwin18.0.0/openssl/1.1.0h-8ca27d37d74/./.stamp_built] Error 2
```

**Comment by nabilwadih** [comment]
experiencing this same issue was wondering if you ever figured out what was causing it?

**Comment by Apj1234** [comment]
https://github.com/ZencashOfficial/Sidechains-SDK.git
